version: 2

models:
  - name: stg_transactions
    columns:
      - name: invoice_id
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: quantity
        tests:
          - not_null
      - name: unit_price
        tests:
          - not_null
      - name: revenue
        tests:
          - not_null

  - name: mart_top_products
    columns:
      - name: product_code
        tests:
          - not_null
      - name: total_revenue
        tests:
          - not_null

  - name: mart_daily_revenue
    columns:
      - name: total_revenue
        tests:
          - not_null

  - name: mart_country_revenue
    columns:
      - name: total_revenue
        tests:
          - not_null
